-- 코드를 작성해주세요
# SELECT D.ID, IFNULL(COUNT(D.ID), 0) AS CHILD_COUNT
# FROM ECOLI_DATA D
# GROUP BY ID
# HAVING CHILD_COUNT IN (SELECT IFNULL(PARENT_ID, 0)
#                          FROM ECOLI_DATA)

SELECT E.ID, IFNULL(C.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY 1) AS C
ON E.ID = C.PARENT_ID