-- 코드를 입력하세요
SELECT  YEAR(SALE.SALES_DATE) YEAR, 
        MONTH(SALE.SALES_DATE) MONTH,
        INFO.GENDER,
        COUNT(DISTINCT INFO.USER_ID) COUNT
FROM ONLINE_SALE SALE INNER JOIN USER_INFO INFO
ON SALE.USER_ID = INFO.USER_ID
WHERE INFO.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3 ASC;