-- 코드를 입력하세요

WITH HISTORY_DURATION AS(
    SELECT *, 
    CASE WHEN(DATEDIFF(END_DATE, START_DATE)+1) BETWEEN 7 AND 29 THEN "7일 이상"
         WHEN(DATEDIFF(END_DATE, START_DATE)+1) BETWEEN 30 AND 89 THEN "30일 이상"
         WHEN(DATEDIFF(END_DATE, START_DATE)+1) >= 90 THEN "90일 이상"
    ELSE 0
    END
    AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT  H.HISTORY_ID, ROUND((DATEDIFF(H.END_DATE, H.START_DATE)+1) * (C.DAILY_FEE * ROUND((1-(IFNULL(P.DISCOUNT_RATE,0)/100)),2)),0) AS FEE
FROM HISTORY_DURATION H LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON H.DURATION_TYPE = P.DURATION_TYPE
AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = "트럭"
ORDER BY 2 DESC, 1 DESC;

