-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F INNER JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
HAVING SUM(J.TOTAL_ORDER + F.TOTAL_ORDER)
ORDER BY SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3;