-- 코드를 입력하세요
SELECT AP.APNT_NO, PT.PT_NAME, AP.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM PATIENT PT LEFT JOIN APPOINTMENT AP
ON PT.PT_NO = AP.PT_NO
LEFT JOIN DOCTOR DR 
ON AP.MDDR_ID = DR.DR_ID
WHERE DATE(AP.APNT_YMD) = '2022-04-13' 
        AND AP.APNT_CNCL_YN = 'N' 
        AND AP.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;