-- 코드를 입력하세요
# SELECT DATE_FORMAT(DATETIME, '%H') HOUR, COUNT(ANIMAL_ID) COUNT
# FROM ANIMAL_OUTS
# GROUP BY 1
# ORDER BY 1 ASC

WITH RECURSIVE TIME AS(
   SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME
    WHERE HOUR < 23
)
SELECT T.HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM TIME T LEFT JOIN ANIMAL_OUTS A
ON T.HOUR =  HOUR(A.DATETIME)
GROUP BY T.HOUR;
