-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') HOUR, COUNT(DATE_FORMAT(DATETIME, '%H')) COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN 9 AND 19
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H') ASC;