-- 코드를 작성해주세요
# SELECT I.ID, N.FISH_NAME, MAX(I.LENGTH)
# FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N
# ON I.FISH_TYPE = N.FISH_TYPE
# GROUP BY I.ID, N.FISH_NAME
# HAVING MAX(LENGTH) > 10

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                  FROM FISH_INFO
                  GROUP BY FISH_TYPE)
AND I.LENGTH > 10
ORDER BY I.ID ASC