-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(HALF.TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF HALF LEFT JOIN ICECREAM_INFO INFO
ON HALF.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY 2 ASC;